---
- name: Gathers facts about remote hosts
  ansible.builtin.setup:
    filter:
    - 'ansible_distribution'
    - 'ansible_os_family'
    - 'ansible_machine_id'
    - 'ansible_distribution_minor_version'
    - 'ansible_distribution_major_version'
  no_log: true

- ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
  - files: &LOOP_FILES
    - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}{{ ansible_distribution_minor_version|d("") }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'default.yml'
    skip: True

- ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
  - files: *LOOP_FILES
    paths: ['os']

- name: Packages
  no_log: true
  set_fact:
    packages: "{{ cargo_packages }}"

- name: Recommendations
  set_fact:
    packages: "{{ packages|union(cargo_recommendations) }}"
  no_log: true
  when: cargo_install_recommendations or cargo_install_all_recommendations

- name: Soft recommendations
  set_fact:
    packages: "{{ packages|union(cargo_soft_recommendations) }}"
  no_log: true
  when: cargo_install_soft_recommendations or cargo_install_all_recommendations

- name: Install cargo packages
  block:
  - community.general.cargo:
      name: "{{ packages }}"
  rescue:
  - community.general.cargo:
      name: "{{ pkg }}"
    loop: "{{ packages }}"
    ignore_errors: true
    loop_control:
      loop_var: 'pkg'
...
